# -*- coding: utf-8 -*-
"""gis710_open_science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NaBJO0e8KLvhUFrfu7NV3XGnPeQmOr1V
"""

print("Hello, World!")